# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload pypi.org

on:
   release:
      types: published
   workflow_dispatch:
      inputs:
         name:
            description: 'reason'
            required:    true
            default:     'any'

jobs:
   build_python:
      runs-on: ${{ matrix.platform }}
      strategy:
         matrix:
            platform: [
                  windows-latest,
                  ubuntu-latest,
                  macos-latest
            ]
            python-version: [
                  3.9,
            ]

      steps:
         -
            uses: actions/checkout@v2
            with:
               submodules: true
         -
            name: Setup Python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
               python-version: ${{ matrix.python-version }}

         -
            name:  Install and Build
            shell: bash
            run:   |
                   python -m pip install -U pip
                   pip install setuptools wheel pytest flake8 twine psutil
         -
            name:  Test and Build for >= 3.6
            shell: bash
            run:   |
                   flake8
                   python setup.py test
                   pip install -e .
                   cd tests && pytest && cd ..
                   python setup.py bdist_wheel
                   python setup.py sdist --formats=gztar
                   twine check --strict dist/*
         -
            name: Save whl file to artifact
            uses: actions/upload-artifact@v2
            with:
               name:           dist
               path:           dist
               retention-days: 5

   publish:
      needs: [ build_python ]
      runs-on: ubuntu-latest
      steps:
         -
            name: download dist from artifact
            uses: actions/download-artifact@v2
            with:
               name: dist
         -
            name:  Publish PyPI
            shell: bash
            env:
               PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
               PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
            run:   |
                   pip install twine
                   twine upload --verbose --skip-existing -u "$TEST_PYPI_USERNAME" -p "$TEST_PYPI_PASSWORD" --repository-url https://test.pypi.org/legacy/ ./*
